[tool.poetry]
name = "deutschland"
version = "0.1.9"
description = ""
license = "Apache-2.0"
authors = ["Lilith Wittmann <mail@lilithwittmann.de>"]
readme = "README.md"
repository = "https://github.com/bundesAPI/deutschland"
include = ["assets/model.h5"]
packages = [
    { include = "deutschland", from = "src" },
]
[tool.poetry.dependencies]
python = "^3.7.1"
Shapely = "^1.8.0"
mapbox-vector-tile = "^1.2.1"
requests = "^2.26.0"
dateparser = "^1.0.0"
gql = "^2.0.0"
boto3 = "^1.18.9"
slugify = "^0.0.1"
Pillow = "^8.3.1"
beautifulsoup4 = "^4.9.3"
lxml = "^4.6.3"
pandas = "^1.3.3"
more-itertools = "^8.10.0"
de-autobahn = {version = "^1.0.4", optional = true}
de-dwd = {version = "^1.0.1", optional = true}
pypresseportal = {version= "^0.1", optional = true}
de-nina = {version= "^1.0.1", optional = true}
de-ladestationen = {version= "^1.0.4", optional = true}
onnxruntime = "^1.10.0"
numpy = "~1.21.0"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/bundesAPI/deutschland/issues"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
pytest = "^6.2.4"

[tool.poetry.extras]
autobahn = ["de-autobahn"]
dwd = ["de-dwd"]
presseportal = ["pypresseportal"]
nina = ["de-nina"]
ladestationen = ["de-ladestationen"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
