name: Run Python 🐍 tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.13","3.9.10","3.9.6","3.9.5","3.9.4","3.9.3","3.9.1","3.9.0","3.8.13","3.8.12","3.8.10","3.8.9","3.8.8","3.8.7","3.8.6","3.8.5","3.8.3","3.8.2","3.8.1","3.8.0","3.7.13","3.7.12","3.7.11","3.7.9","3.7.8","3.7.6","3.7.5","3.7.1","3.6.12","3.6.11","3.6.10","3.6.9"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .[all]
      - name: Test with pytest
        run: |
          pytest 
